export interface AddDevice {
  deviceId: null | number,
  siteId: null | number,
  deviceUnitId: string,
  deviceCallFreq: null |number,
  deviceMode: string,
  workingDays: string,
  getlogs: null | number,
  width: null | number,
  height: null | number,
  modelName: string,
  resolution: string,
  threshold: string,
  maxNo: null | number,
  objectName: string,
  refreshRules: string,
  displayOn: string,
  adsHours: string,
  weather_interval: string,
  cameraId: string,
  createdBy: null | number,
  modifiedBy: null | number,
  remarks: string
}
